"""change the publish_date

Revision ID: 69d3f9dd1dbc
Revises: 3dae39c2a7ac
Create Date: 2026-03-19 01:34:28.505948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "69d3f9dd1dbc"
down_revision: Union[str, Sequence[str], None] = "3dae39c2a7ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "books",
        "published_date",
        existing_type=sa.VARCHAR(),
        type_=sa.DATE(),
        nullable=True,
        postgresql_using="published_date::date",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "published_date",
        existing_type=sa.DATE(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
